languageCode: "en-gb"

baseURL: "http://docs.yourcompany.com:1313"
title: "Your Company"
buildDrafts: true
theme: ../../../graphia-minimal-theme
#relativeURLs: true
publishDir: ../dist
fencedCode: true
preserveTaxonomyNames: true

pygmentsCodeFences: true
pygmentsUseClasses: true

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

Languages:
  en:
    name: English
    weight: 0
    flag: ğŸ‡¬ğŸ‡§
    title: Your Company

  fr:
    name: FranÃ§ais
    weight: 1
    flag: ğŸ‡«ğŸ‡·

  de:
    name: Deutsch
    weight: 1
    flag: ğŸ‡©ğŸ‡ª

  es:
    name: EspaÃ±ol
    weight: 1
    flag: ğŸ‡ªğŸ‡¸

  uk:
    name: ÑƒĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ° Ğ¼Ğ¾Ğ²Ğ°
    weight: 1
    flag: ğŸ‡ºğŸ‡¦
    title: Ğ’Ğ°ÑˆĞ° ĞºĞ¾Ğ¼Ğ¿Ğ°Ğ½Ñ–Ñ
