languageCode: "en-gb"

baseURL: "http://localhost:1313"
buildDrafts: true
theme: ../../../graphia-minimal-theme
relativeURLs: true
publishDir: ../dist
fencedCode: true

pygmentsCodeFences: true
pygmentsUseClasses: true

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

Languages:
  en:
    title: "English"
    weight: 0
    flag: ğŸ‡¬ğŸ‡§

  fr:
    title: "French"
    weight: 1
    flag: ğŸ‡«ğŸ‡·

  de:
    title: "German"
    weight: 1
    flag: ğŸ‡©ğŸ‡ª
  es:
    title: "Spanish"
    weight: 1
    flag: ğŸ‡ªğŸ‡¸
